### PR TITLE
Import "Add cache flushes to GX2sploit" from libwiiu commit 0e67eb1

### PR DESCRIPTION
**Pull request by drizzt**

### CODE REVIEW

**Comment by dimok789** [comment]
Yeah I know about that one. I suggested it to MN1. It actually doesn't fix the problem it seems. I am still looking for the issue with the freeze. Just can't test it since I dont have a 5.5.1

**Comment by drizzt** [comment]
I don't know if it's a "placebo effect" or just "statistics", but with the cache flushes it seems I have a best load ratio

**Comment by mariogamer2** [comment]
Ah this is why I always freeze...

**Comment by dimok789** [comment]
Its there now.

**Pull request closed without merging**
