### PR TITLE
changed compatibility with dlc for mii maker mode.

### PR DESCRIPTION
**Pull request by andrew134**

### CODE REVIEW

**Comment by CreeperMario** [comment]
Were you able to successfully build and run this on your own console?
Travis says that your code fails to build.
```
/home/travis/build/dimok789/loadiine_gx2/src/menu/MainWindow.cpp:527:5: error: duplicate case value
     case LOADIINE_MODE_SMASH_BROS:
     ^
/home/travis/build/dimok789/loadiine_gx2/src/menu/MainWindow.cpp:523:5: error: previously used here
     case LOADIINE_MODE_MII_MAKER:
     ^
make[1]: *** [MainWindow.o] Error 1
make: *** [build] Error 2
```

**Comment by andrew134** [comment]
I thought I'll try to edit the source code of loadline so I can load dlc from mii maker mode, but anyway , I'm not very good at programming.

**Comment by andrew134** [comment]
by the way, you seem like the only person who replies to my comments and no one else, why is that?

**Comment by Maschell** [comment]
This changes makes no sense, you can't simply changed the defines. With this loadiine getting confused how to boot the game and the config files are broken..

DLC in Mii Maker mode is already supported, not need for changes

**Comment by andrew134** [comment]
I was just trying to make dlc free because I don't want to buy game an dlc . would it be possible if you could add support for that so I can play it in games like mario kaart 8 in mii maker mode. some people in pages like darkumbra made dumps of the dlc.

**Comment by mariogamer2** [comment]
I think dimok789 do not want to do this...

**Comment by andrew134** [comment]
why not???? I prefer to have the dlc installed with the other tracks in mario kart 8 by downloading it from a website rather than have them changed and because I don't  have enough money to pay for the game. that's why I prefer to have free dlc so I don;t pay money for it. I know it's piracy but I would really like that just for this game.

**Comment by mariogamer2** [comment]
I do not remember why exactly,but he do not support pirating...

**Comment by Maschell** [comment]
Even when MK8 with the newest update would work on loadiine via MiiMaker, you will still need to buy the game. The files on the SDCard are not enough. Loadiine is a BACKUP loader, not a magic piracy machine

**Comment by andrew134** [comment]
but how can I make mario kart 8 work with the games newest update in mii maker mode because I have the latest loadline nightly.

**Comment by CreeperMario** [comment]
Mario Kart 8 screws up the memory mapping or something, it is not possible to run updated versions of Mario Kart 8 within Mii Maker. You must purchase a copy of Super Smash Bros. for Wii U, either a disc version or an eShop download.

**Comment by Maschell** [comment]
Everything is said, every further comment will be deleted.

**Pull request closed without merging**
