### PR TITLE
Further changes for FW 4.1.0 and 4.0.0

### PR DESCRIPTION
**Pull request by Nougat-Police**
+ installer support for 4.X.X added
+ new OS specific function addresses defined<br>
(_addr_sgIsLoadingBuffer_ and _addr_gDynloadInitialized_)
+ OS specific addresses for 4.1.0 and 4.0.X added
+ memory area table for 4.1.0 added

Note: There is a bug in loadiine's sound feature that causes a crash (freezes with a black screen) when loading any game or exiting to Mii Maker / Home Menu. I am unable to fix it and my workaround is just removing the sound part.

### CODE REVIEW

**Comment by dimok789** [comment]
I don't really like the solution of removing all sounds just for 4.0.0. There must be a better way. Could you maybe narrow down what function is actually causing issues in the sounds with the debugger and then I might be able to help you fix it. Obviously I cant do that.

From my point of view there is no bug on loadiine gx2 sound feature. There might be something that we use, that is not available in the same form on 4.0.0 (even if it is just a changed call to the same functions) or it is something that has to be used different on 4.0.0 but I dont think we have an issue in the sound code for 5.3.2 as that runs without any issues.

**Comment by BinaryShrub** [comment]
Side note, I have issues with a popping sound with the default audio on 5.3.2 so I disabled it by pointing to a blank file

**Comment by dimok789** [comment]
Well it is still removing the sound parts of loadiine gx2. If i merge that in everyone on other firmwares would not have any sounds either. Besides you shouldnt need to remove all those functions and classes. The only parts you need to change are inside SoundHandler.cpp

Just add a if(OS_FIRMWARE <= 410) return; on the following function
void SoundHandler::executeThread()

and return NULL on:

SoundDecoder * SoundHandler::GetSoundDecoder(const char * filepath)
SoundDecoder * SoundHandler::GetSoundDecoder(const u8 * sound, int length)

That removes all sounds. If you still have issue after doing that, then some NULL pointer isnt catched in the sound code of loadiine gx2. I think i did safety checks everywhere by now though.

**Comment by dimok789** [comment]
A proper fix with sound support for < 5.x.x is on the way by andriy921. Closing this one.

**Pull request closed without merging**
