### PR TITLE
Added VPAD left stick as alternate menu navigation

### PR DESCRIPTION
**Pull request by littlebalup**
note : vpad stick emulation as d-pad buttons (not axis)

### CODE REVIEW

**Comment by dimok789** [comment]
Looks good, except can you change one thing:

if((controller->data.buttons_h | controller->data.buttons_d) & BUTTON_UP || (controller->data.buttons_h | controller->data.buttons_d) & STICK_L_UP)

This is really not necessary to do two steps. Its a bit operation so you can just do this:
if( (controller->data.buttons_h | controller->data.buttons_d) & (BUTTON_UP | STICK_L_UP) )

If you could change it, that would be great as I dont have time today and tommorow to do stuff, but I could just make auto merge your pull request from the web interface.

**Comment by littlebalup** [comment]
Yes, no problem. Good point. I'll comit this right now.

**Comment by littlebalup** [comment]
done ;)

**Comment by dimok789** [comment]
Ok adding

**Pull request merged**
