### PR TITLE
replaced tabs with 4 spaces and all the same indent 4 spaces

### PR DESCRIPTION
**Pull request by FunThomas76**
i hope it looks good now
notepad++ can show tabs ands spaces and is a real nice editor if someone wants to try

### CODE REVIEW

**Comment by FunThomas76** [comment]
so i have added a fix for issue Icon Carousel #30
The Icon Carousel is in now in the same order like the Cover carousel.

**Comment by dimok789** [comment]
Actually its the cover carousel that is wrong in my opinion. The Icon Carousel is a perfect circle calculation. The cover carousel was a quick and dirty port from usbloader gx for which i didnt have much time.

**Comment by FunThomas76** [comment]
ok then i will close the pull request
i use the most time the cover carousel
dont need the small icons -> i'm a bit older need some bigger picture :)

**Comment by dimok789** [comment]
No i didnt mean you need to close the pull request. The issue is still present. I just think I need to adapt the rotation of the cover carousel and not icon carousel. Maybe I am wrong and my is not making any sense and we have to adapt the icon carsouel. I just wanted to look at it first.

I hope its ok if I reopen it.

**Pull request closed without merging**
